# Generated by Django 4.2.2 on 2023-06-08 14:59

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_createdat_tweet_updated_tweet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[tweets.models.validation_content]),
        ),
    ]
